name: check-cmake

on:
    push:
        paths:
            - "**/CMakeLists.txt"
            - "**/*.py"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    linux:
        runs-on: "ubuntu-24.04"

        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup virtualenv and run Check CMake integration test
              run: |
                  sudo apt update
                  sudo apt install -y python3-virtualenv
                  python3 -m virtualenv test_env
                  source test_env/bin/activate

                  pip install misk>=0.8.1 colorama
                  python3 test-check-cmake.py --testdir tests
